### ISSUE TITLE
support removing servers from meta group

### ISSUE THREAD

**Issue by ripienaar** [nats-io/jsm.go#216]
https://github.com/nats-io/nats-server/pull/1947/files#diff-9c075c47b0690a821ad35caa26308b69adeb132042f062eef75513db2a26638aR170

Also the JSAdvisoryServerRemoved

Will DISABLE JETSTREAM ON THE TARGET SERVER. Add confirmation prompts etc, warn about affected streams/consumers before

 - [x] jsm (https://github.com/nats-io/jsm.go/pull/219, https://github.com/nats-io/jsm.go/pull/220)
 - [x] cli https://github.com/nats-io/natscli/pull/99
 - [x] docs https://github.com/nats-io/jetstream/pull/492
 - [x] schemas https://github.com/nats-io/jetstream/pull/488, https://github.com/nats-io/jetstream/pull/489
